name: Build and run E2E Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PORT: ${{ secrets.APP_PORT }}
      DB_PORT: 5432
      DB_USERNAME:  ${{ secrets.POSTGRES_USER }}
      DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      DB_NAME:  ${{ secrets.POSTGRES_DB }}
      DB_HOST: localhost

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER:  ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD:  ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB:  ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up e2e Database
        run: |
          npm install -g pg
          PGPASSWORD="${{ secrets.POSTGRES_PASSWORD }}" psql -h localhost -U postgres -d test < test/sql/initial.sql

      # Performs a clean installation of all dependencies in the `package.json` file
      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run Tests
        run: npm run test:e2e:json

      - name: Process jest results with default
        if: always()
        uses: im-open/process-jest-test-results@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          results-file: 'test/jest-results.json'
