name: Build and run E2E Tests
run-name: Pull request ${{ github.event.pull_request.title }} (${{ github.event.pull_request.head.label}})

on:
  pull_request:
    branches:
      - master

env:
  PORT: ${{ secrets.APP_PORT }}
  DB_PORT: 5432
  DB_USERNAME:  ${{ secrets.POSTGRES_USER }}
  DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  DB_NAME:  ${{ secrets.POSTGRES_DB }}
  DB_HOST: localhost

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

  test:
    uses: ../e2e-job.yml
